/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import DAO.BienLaiDAO;
import DAO.KhachHangDAO;
import Helpers.MessaDialogHelper;
import Models.BienLai;
import Models.KhachHang;
import Models.ListKhachHang;
import static Views.QuanLyHoaDon.listBienLai;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class QuanlyKhachHang extends javax.swing.JPanel {

    /**
     * Creates new form QuanlyKhachHang
     */
    ListKhachHang listKhachHang = new ListKhachHang();
    public QuanlyKhachHang() {
        initComponents();
        init();
    }
    void init()
    {
        listKhachHang.setListKhachHang(KhachHangDAO.GetKhachHangs());
        doHienThi(listKhachHang.getListKhachHang());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMaKh = new javax.swing.JTextField();
        txtHoten = new javax.swing.JTextField();
        txtDiachi = new javax.swing.JTextField();
        txtMacongto = new javax.swing.JTextField();
        txtSdt = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabledata = new javax.swing.JTable();
        btnTaomoi = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnCapnhat = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jButtonTim = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/target.png"))); // NOI18N
        jLabel1.setText("QUẢN LÝ KHÁCH HÀNG");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("MÃ KH");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("HỌ TÊN");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel4.setText("ĐỊA CHỈ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel5.setText("MÃ SỐ CÔNG TƠ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel6.setText("SĐT");

        txtMaKh.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtMaKh.setName(""); // NOI18N

        txtHoten.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtDiachi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtMacongto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtSdt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTabledata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MÃ KH", "HỌ TÊN", "ĐỊA CHỈ", "MÃ SỐ CÔNG TƠ", "SĐT"
            }
        ));
        jTabledata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTabledataMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTabledata);

        btnTaomoi.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnTaomoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/add (2).png"))); // NOI18N
        btnTaomoi.setText("Refresh");
        btnTaomoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaomoiActionPerformed(evt);
            }
        });

        btnLuu.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/add.png"))); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnCapnhat.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnCapnhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/edit.png"))); // NOI18N
        btnCapnhat.setText("Cập Nhật");
        btnCapnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapnhatActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/baseline_delete_forever_black_24dp.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jButtonTim.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButtonTim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/search.png"))); // NOI18N
        jButtonTim.setText("Tìm kiếm");
        jButtonTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addComponent(jSeparator2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 749, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel3)
                                        .addGap(97, 97, 97))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtHoten, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMaKh, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnTaomoi, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(btnCapnhat)
                                .addGap(57, 57, 57)
                                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(jButtonTim))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(45, 45, 45)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMacongto, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMaKh, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(txtDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTaomoi)
                            .addComponent(btnLuu)
                            .addComponent(btnCapnhat)
                            .addComponent(btnXoa)
                            .addComponent(jButtonTim))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtMacongto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1052, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 3, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 4, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 584, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTimActionPerformed
        // TODO add your handling code here:
        doSearch();
    }//GEN-LAST:event_jButtonTimActionPerformed

    private void btnCapnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapnhatActionPerformed
        // TODO add your handling code here:
         doUpdate();
    }//GEN-LAST:event_btnCapnhatActionPerformed

    private void jTabledataMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabledataMousePressed
        // TODO add your handling code here:
        getSelectRow();
    }//GEN-LAST:event_jTabledataMousePressed

    private void btnTaomoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaomoiActionPerformed
        // TODO add your handling code here:
        doClear();
    }//GEN-LAST:event_btnTaomoiActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        doSave();
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        doDelete();
    }//GEN-LAST:event_btnXoaActionPerformed
   
    
    void doSave()
    {
        int index = listKhachHang.getKhachHangByMaKH(txtMaKh.getText());
        if(index >= 0) 
        {
            
            MessaDialogHelper.showMessageDialog(null, "Khach hang Da ton tai", "Da ton tai");
            return;
        }
        else
        {
            if(listKhachHang.CheckMaCongTo(txtMacongto.getText())<0)
            {
                MessaDialogHelper.showMessageDialog(null, "Ma cong to Da ton tai", "Da ton tai");
                return;
            }
        }
        KhachHang newKhachHang = new KhachHang();
        if(txtDiachi.getText().isEmpty() || txtHoten.getText().isEmpty()
                || txtMaKh.getText().isEmpty() || txtMacongto.getText().isEmpty()
                || txtSdt.getText().isEmpty())
        {
            MessaDialogHelper.showErrorDialog(null, "Thong tin con trong", "Nhap khong du");
            return;
        }
        newKhachHang.setMaKH(txtMaKh.getText());
        newKhachHang.setMaSoCongTo(txtMacongto.getText());
        newKhachHang.setSDT(txtSdt.getText());
        newKhachHang.setSoNha(txtDiachi.getText());
        newKhachHang.setTenKH(txtHoten.getText());
        try {
            KhachHangDAO.Insert(newKhachHang);
            listKhachHang.AddKhachHang(newKhachHang);
            doHienThi(listKhachHang.getListKhachHang());
        } catch (Exception e) {
        }
        
    }
    void doHienThi(ArrayList<KhachHang> list)
    {
        DefaultTableModel model = new DefaultTableModel();
        model = (DefaultTableModel) jTabledata.getModel();
        model.setRowCount(0);
        for (KhachHang khachHang : list) {
            Object[] row = {
                khachHang.getMaKH(),khachHang.getTenKH(),khachHang.getSoNha(),khachHang.getMaSoCongTo(),khachHang.getSDT()
            };
            model.addRow(row);
        }
        jTabledata.setModel(model);
    }
    void doDelete()
    {
        int index = listKhachHang.getKhachHangByMaKH(txtMaKh.getText());
        if(index == -1) 
        {
            MessaDialogHelper.showMessageDialog(null, "Khong ton tai", "Not Found");
            return;
        }
        if(BienLaiDAO.SearchKH(txtMaKh.getText()))
        {
            MessaDialogHelper.showErrorDialog(null, "Some thing used this", "Constains");
            return;
        }
        if(MessaDialogHelper.showConfirmDialog(null, "Co chac muon xoa khong", "Delete") == 0)
        {
            KhachHangDAO.Delete(txtMaKh.getText());
            listKhachHang.RemoveByIndex(index);
            doHienThi(listKhachHang.getListKhachHang());
        }
    }
    void doClear()
    {
        txtMaKh.setText("");
        txtHoten.setText("");
        txtDiachi.setText("");
        txtMacongto.setText("");
        txtSdt.setText("");
        doHienThi(listKhachHang.getListKhachHang());
    }
    void getSelectRow()
    {
        int row = jTabledata.getSelectedRow();
         txtMaKh.setText(String.valueOf(jTabledata.getModel().getValueAt(row, 0)));
         txtHoten.setText(String.valueOf(jTabledata.getModel().getValueAt(row, 1))); 
         txtDiachi.setText(String.valueOf(jTabledata.getModel().getValueAt(row, 2))); 
         txtMacongto.setText(String.valueOf(jTabledata.getModel().getValueAt(row, 3))); 
         txtSdt.setText(String.valueOf(jTabledata.getModel().getValueAt(row, 4))); 
    }
    void doSearch()
    {
        if(!txtMaKh.getText().isEmpty())
        {
            doHienThi(listKhachHang.SearchByMaKHList(txtMaKh.getText()));
        }
        else if(!txtSdt.getText().isEmpty())
        {
             doHienThi(listKhachHang.SearchBySDTList(txtSdt.getText()));
        }
        else if(!txtMacongto.getText().isEmpty())
        {
             doHienThi(listKhachHang.SearchByMaCongToList(txtMacongto.getText()));
        }
        else
        {
            MessaDialogHelper.showMessageDialog(null, "Chua nhap Day du", "Input Fail");
        }
        
    }
    void doUpdate()
    {
        int index = listKhachHang.getKhachHangByMaKH(txtMaKh.getText());
        if(index == -1) 
        {
            MessaDialogHelper.showMessageDialog(null, "Khong ton tai", "Not Found");
            return;
        }
        KhachHang newKhachHang = listKhachHang.getListKhachHang().get(index);
        System.err.println(index);
        if(!txtMaKh.getText().isEmpty())
        {
            newKhachHang.setMaKH(txtMaKh.getText());
        }
        if(!txtHoten.getText().isEmpty())
        {
            newKhachHang.setTenKH(txtHoten.getText());
        }
        
        if(!txtDiachi.getText().isEmpty())
        {
            newKhachHang.setSoNha(txtDiachi.getText());
        }
        if(!txtMacongto.getText().isEmpty())
        {
            newKhachHang.setMaSoCongTo(txtMacongto.getText());
        }
        if(!txtSdt.getText().isEmpty())
        {
            newKhachHang.setSDT(txtSdt.getText());
        }
        KhachHangDAO.Update(newKhachHang);
        listKhachHang.getListKhachHang().set(index,newKhachHang);
        doHienThi(listKhachHang.getListKhachHang());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapnhat;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnTaomoi;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton jButtonTim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTabledata;
    private javax.swing.JTextField txtDiachi;
    private javax.swing.JTextField txtHoten;
    private javax.swing.JTextField txtMaKh;
    private javax.swing.JTextField txtMacongto;
    private javax.swing.JTextField txtSdt;
    // End of variables declaration//GEN-END:variables
}
