/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Helpers.MessaDialogHelper;

/**
 *
 * @author AnhDT
 */
public class TrangAd extends javax.swing.JFrame {

    /**
     * Creates new form TrangAd
     */
    QuanLyHoaDon hd = new QuanLyHoaDon();
    QuanlyKhachHang kh = new QuanlyKhachHang();
    QuanLyNhanVien nv = new QuanLyNhanVien();
    QuanLyPhanHoiPanel ph = new QuanLyPhanHoiPanel();
    public TrangAd() {
        initComponents();
        tpMainBoard.add(nv);
        tpMainBoard.add(kh);
        tpMainBoard.add(hd);
        tpMainBoard.add(ph);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnDangXuat = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        btnQLNV = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        btnQLKH = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        btnQLHD = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JToolBar.Separator();
        btnQLPH = new javax.swing.JButton();
        tpMainBoard = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuDangXuat = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mnuThoat = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuQLNV = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuQLKH = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuQLHD = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnuQLPH = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnuNoiDung = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mnuGioiThieu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        btnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/logout.png"))); // NOI18N
        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.setFocusable(false);
        btnDangXuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDangXuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnDangXuat);
        jToolBar1.add(jSeparator6);

        btnQLNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/ambulance64.png"))); // NOI18N
        btnQLNV.setText("Quản lý nhân viên");
        btnQLNV.setFocusable(false);
        btnQLNV.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLNV.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnQLNV);
        jToolBar1.add(jSeparator7);

        btnQLKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/customer-review.png"))); // NOI18N
        btnQLKH.setText("Quản lý khách hàng");
        btnQLKH.setFocusable(false);
        btnQLKH.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLKH.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnQLKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLKHActionPerformed(evt);
            }
        });
        jToolBar1.add(btnQLKH);
        jToolBar1.add(jSeparator8);

        btnQLHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/bill.png"))); // NOI18N
        btnQLHD.setText("Quản lý hóa đơn");
        btnQLHD.setFocusable(false);
        btnQLHD.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLHD.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnQLHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLHDActionPerformed(evt);
            }
        });
        jToolBar1.add(btnQLHD);
        jToolBar1.add(jSeparator9);

        btnQLPH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/telemarketer.png"))); // NOI18N
        btnQLPH.setText("Quản lý phản hồi");
        btnQLPH.setFocusable(false);
        btnQLPH.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLPH.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnQLPH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLPHActionPerformed(evt);
            }
        });
        jToolBar1.add(btnQLPH);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/icons8-system-task-16.png"))); // NOI18N
        jMenu1.setText("Hệ thống");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        mnuDangXuat.setText("Đăng xuất");
        jMenu1.add(mnuDangXuat);
        jMenu1.add(jSeparator4);

        mnuThoat.setText("Thoát");
        jMenu1.add(mnuThoat);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/ic_add_user.png"))); // NOI18N
        jMenu2.setText("Quản lý");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        mnuQLNV.setText("Quản lý nhân viên");
        jMenu2.add(mnuQLNV);
        jMenu2.add(jSeparator1);

        mnuQLKH.setText("Quản lý khách hàng");
        jMenu2.add(mnuQLKH);
        jMenu2.add(jSeparator2);

        mnuQLHD.setText("Quản lý hóa đơn");
        jMenu2.add(mnuQLHD);
        jMenu2.add(jSeparator3);

        mnuQLPH.setText("Quản lý phản hồi khách hàng");
        jMenu2.add(mnuQLPH);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/ic_support.png"))); // NOI18N
        jMenu3.setText("Trợ giúp");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        mnuNoiDung.setText("Nội dung trợ giúp");
        jMenu3.add(mnuNoiDung);
        jMenu3.add(jSeparator5);

        mnuGioiThieu.setText("Giới thiệu");
        jMenu3.add(mnuGioiThieu);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1319, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(tpMainBoard)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tpMainBoard, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQLPHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLPHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQLPHActionPerformed

    private void btnQLKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLKHActionPerformed
        // TODO add your handling code here:
        tpMainBoard.setSelectedIndex(1);
    }//GEN-LAST:event_btnQLKHActionPerformed

    private void btnQLHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLHDActionPerformed
        // TODO add your handling code here:
        tpMainBoard.setSelectedIndex(2);
    }//GEN-LAST:event_btnQLHDActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnQLHD;
    private javax.swing.JButton btnQLKH;
    private javax.swing.JButton btnQLNV;
    private javax.swing.JButton btnQLPH;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar.Separator jSeparator9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem mnuDangXuat;
    private javax.swing.JMenuItem mnuGioiThieu;
    private javax.swing.JMenuItem mnuNoiDung;
    private javax.swing.JMenuItem mnuQLHD;
    private javax.swing.JMenuItem mnuQLKH;
    private javax.swing.JMenuItem mnuQLNV;
    private javax.swing.JMenuItem mnuQLPH;
    private javax.swing.JMenuItem mnuThoat;
    private javax.swing.JTabbedPane tpMainBoard;
    // End of variables declaration//GEN-END:variables
}
